class_info_category:
  0:
  - ConstructionSite
  - '#B5E4FF'
  1:
  - Building
  - '#C5FEB6'
  2:
  - BuildingDistortion
  - '#900C3F'
  3:
  - GreenAreas
  - '#FEE8C2'
  4:
  - RoadAsphalt
  - '#FAB6FE'
  5:
  - Forest
  - '#C0B2FD'
  6:
  - WaterBasin
  - '#F4FFB3'
  7:
  - Path
  - '#EED7FF'
  8:
  - MeadowPasture
  - '#CEFEEB'
  9:
  - SealedObjects
  - '#FED7D1'
class_info_sealed:
  0:
  - unsealed
  - '#B6FFB8'
  1:
  - sealed
  - '#FDECCF'
  2:
  - unknown
  - '#FBB4AE'
diff_info:
  10:
  - Correct Prediction
  - '#7CB9E8'
  11:
  - Incorrect Prediction
  - '#FF6F91'
rgb_norm_settings:
  '1':
    clip_max: 0.95
    clip_min: 0.1
    gamma: 0.7
  '10':
    clip_max: 0.8
    clip_min: 0.07
    gamma: 0.4
  '11':
    clip_max: 0.8
    clip_min: 0.07
    gamma: 0.4
  '12':
    clip_max: 0.8
    clip_min: 0.2
    gamma: 0.25
  '2':
    clip_max: 0.94
    clip_min: 0.0
    gamma: 0.65
  '3':
    clip_max: 1.0
    clip_min: 0.0
    gamma: 0.8
  '4':
    clip_max: 1.0
    clip_min: 0.0
    gamma: 0.8
  '5':
    clip_max: 0.8
    clip_min: 0.07
    gamma: 0.4
  '6':
    clip_max: 0.8
    clip_min: 0.07
    gamma: 0.4
  '7':
    clip_max: 0.8
    clip_min: 0.07
    gamma: 0.4
  '8':
    clip_max: 0.8
    clip_min: 0.2
    gamma: 0.25
  '9':
    clip_max: 0.8
    clip_min: 0.07
    gamma: 0.4
